---
- name: Get uptime on remote servers
  hosts: all_instances
  gather_facts: no
  tasks:
    - name: Execute uptime command
      command: sudo uptime
      register: uptime_output

    - name: Show uptime output
      debug:
        msg: "Uptime: {{ uptime_output.stdout }}"